#ifndef CHALLENGE_H
#define CHALLENGE_H

#include "states/states.h"

/* Challenge Mode State
 * Simple text-based 16x8 grid navigation
 * . = locked, O = unlocked, X = cleared
 * Display: 2 chars per cell (char + space)
 */

#define CHALLENGE_GRID_WIDTH   16
#define CHALLENGE_GRID_HEIGHT   8
#define CHALLENGE_LEVEL_COUNT 128
#define CHALLENGE_LEVEL_INVALID 255
#define CHALLENGE_TUTORIAL_ENTRY_ID  (2 * CHALLENGE_GRID_WIDTH)

typedef enum ChallengeLevelId {
	CHALLENGE_LEVEL_START = 0,
	CHALLENGE_LEVEL_ERSTE_LINIE,
	CHALLENGE_LEVEL_DOPPELBAU,
	CHALLENGE_LEVEL_VIERER_CHALLENGE,
	CHALLENGE_LEVEL_PUNKTESAMMLER,
	CHALLENGE_LEVEL_30_SEKUNDEN,
	CHALLENGE_LEVEL_LUECKENSPIEL,
	CHALLENGE_LEVEL_HERZ_SAMMLER,
	CHALLENGE_LEVEL_1000ER_SPRUNG,
	CHALLENGE_LEVEL_SCHNELLBAHN,
	CHALLENGE_LEVEL_MUELLBAU_1,
	CHALLENGE_LEVEL_PUNKTE_VS_ZEIT,
	CHALLENGE_LEVEL_DOPPEL_MUELL,
	CHALLENGE_LEVEL_ITEM_PARTY,
	CHALLENGE_LEVEL_BOARD_KONTROLLE,
	CHALLENGE_LEVEL_KURZ_SPRINT,
	CHALLENGE_LEVEL_TRASH_UEBERLEBEN,
	CHALLENGE_LEVEL_HERZ_UND_SCHAEDEL,
	CHALLENGE_LEVEL_5000ER_MARK,
	CHALLENGE_LEVEL_90_SEKUNDEN_SPIEL,
	CHALLENGE_LEVEL_GESCHWINDIGKEIT_1,
	CHALLENGE_LEVEL_MUELL_DUELL,
	CHALLENGE_LEVEL_SAUBERES_SPIEL,
	CHALLENGE_LEVEL_GENAU_5,
	CHALLENGE_LEVEL_MIX_EINSTIEG,
	CHALLENGE_LEVEL_HERZEN_GLEICH_SKULLS,
	CHALLENGE_LEVEL_TEMPO_GRENZE,
	CHALLENGE_LEVEL_MUELL_WELLE,
	CHALLENGE_LEVEL_LANGSAM_UND_SICHER,
	CHALLENGE_LEVEL_ALLES_MIX,
	CHALLENGE_LEVEL_SPRINT_FINALE,
	CHALLENGE_LEVEL_LEICHT_FREISCHRIFT,
	CHALLENGE_LEVEL_GESCHWINDIGKEIT_2,
	CHALLENGE_LEVEL_MUELL_EXPERTE,
	CHALLENGE_LEVEL_HYBRID_SPRINT,
	CHALLENGE_LEVEL_UEBERLEBENS_TRAINING,
	CHALLENGE_LEVEL_SCHAEDEL_SAMMLER,
	CHALLENGE_LEVEL_SAUBERMACHER,
	CHALLENGE_LEVEL_KETTENREAKTION,
	CHALLENGE_LEVEL_SCHNELL_MUELL,
	CHALLENGE_LEVEL_ZEIT_DRUCK,
	CHALLENGE_LEVEL_GEGENSAETZE,
	CHALLENGE_LEVEL_UEBELKEIT_TEST,
	CHALLENGE_LEVEL_GENAU_7,
	CHALLENGE_LEVEL_10K_PUNKTE,
	CHALLENGE_LEVEL_AUSDAUER_MITTEL,
	CHALLENGE_LEVEL_HYBRID_MUELL,
	CHALLENGE_LEVEL_KETTENWELLE,
	CHALLENGE_LEVEL_SPEED_7_WARM,
	CHALLENGE_LEVEL_HOHER_MUELL,
	CHALLENGE_LEVEL_CHAOTEN_QUIZ,
	CHALLENGE_LEVEL_GESAMT_MIX,
	CHALLENGE_LEVEL_PRAEZISION,
	CHALLENGE_LEVEL_HERZEN_FLUT,
	CHALLENGE_LEVEL_SCHAEDEL_VERMEIDEN,
	CHALLENGE_LEVEL_JETZTZEIT,
	CHALLENGE_LEVEL_MUELL_WELT,
	CHALLENGE_LEVEL_HYBRID_FAST,
	CHALLENGE_LEVEL_CHAIN_MASTER,
	CHALLENGE_LEVEL_SCHWER_MIX,
	CHALLENGE_LEVEL_UEBERLEBENS_MITTEL,
	CHALLENGE_LEVEL_DREI_ZIELE,
	CHALLENGE_LEVEL_SPEED_CHAMPION,
	CHALLENGE_LEVEL_FINALE_MITTEL,
	CHALLENGE_LEVEL_GESCHWINDIGKEIT_8,
	CHALLENGE_LEVEL_MUELL_INFERNO,
	CHALLENGE_LEVEL_CHAOS_STORM,
	CHALLENGE_LEVEL_30_SEKUNDEN_SPRINT,
	CHALLENGE_LEVEL_HERZEN_JAGD,
	CHALLENGE_LEVEL_SCHAEDEL_MINFIELD,
	CHALLENGE_LEVEL_SAUBERMACHER_SCHWER,
	CHALLENGE_LEVEL_6X_CHAIN,
	CHALLENGE_LEVEL_ZEITDRUCK_HOELLE,
	CHALLENGE_LEVEL_PYRAMIDEN_BAU,
	CHALLENGE_LEVEL_MUELL_CHAOS,
	CHALLENGE_LEVEL_ITEM_BALLETT,
	CHALLENGE_LEVEL_20K_PUNKTE,
	CHALLENGE_LEVEL_UEBERLEBENS_HART,
	CHALLENGE_LEVEL_ALLES_KOMBO,
	CHALLENGE_LEVEL_SPEED_9_INTRO,
	CHALLENGE_LEVEL_SCHAEDEL_FLOOD,
	CHALLENGE_LEVEL_40_SEKUNDEN_DEAL,
	CHALLENGE_LEVEL_HYBRID_HELL,
	CHALLENGE_LEVEL_EXAKT_9,
	CHALLENGE_LEVEL_7X_CHAIN_ZIEL,
	CHALLENGE_LEVEL_BOARD_EXPLOSION,
	CHALLENGE_LEVEL_TEMPO_UHR,
	CHALLENGE_LEVEL_ALLES_14_LINIEN,
	CHALLENGE_LEVEL_FINALE_CHAOS,
	CHALLENGE_LEVEL_ITEM_MASCHINE,
	CHALLENGE_LEVEL_30K_MARK,
	CHALLENGE_LEVEL_UEBERLEBEN_HARD,
	CHALLENGE_LEVEL_HYBRID_15,
	CHALLENGE_LEVEL_TRIPLE_ZIEL,
	CHALLENGE_LEVEL_PRAEZISION_EXTREM,
	CHALLENGE_LEVEL_HARD_CAPSTONE,
	CHALLENGE_LEVEL_GESCHWINDIGKEIT_HOELLE,
	CHALLENGE_LEVEL_MUELL_APOKALYPSE,
	CHALLENGE_LEVEL_CHAOS_KERN,
	CHALLENGE_LEVEL_20_SEKUNDEN_DEAL,
	CHALLENGE_LEVEL_HERZEN_MARATHON,
	CHALLENGE_LEVEL_SCHAEDEL_ALBTRAUM,
	CHALLENGE_LEVEL_SAUBERMACHER_INFINITY,
	CHALLENGE_LEVEL_8X_CHAIN_LEGENDARY,
	CHALLENGE_LEVEL_50_SEKUNDEN_INFERNO,
	CHALLENGE_LEVEL_PYRAMIDEN_MEGA,
	CHALLENGE_LEVEL_MUELL_APOKALYPSE_2,
	CHALLENGE_LEVEL_ITEM_CHAOS_BALLETT,
	CHALLENGE_LEVEL_50K_PUNKTE,
	CHALLENGE_LEVEL_UEBERLEBENS_LEGENDAER,
	CHALLENGE_LEVEL_ULTRA_KOMBO,
	CHALLENGE_LEVEL_SPEED_9_MEISTER,
	CHALLENGE_LEVEL_SCHAEDEL_PARADIES,
	CHALLENGE_LEVEL_30_SEKUNDEN_LEGENDAER,
	CHALLENGE_LEVEL_HYBRID_SUPREME,
	CHALLENGE_LEVEL_EXAKT_20,
	CHALLENGE_LEVEL_9X_CHAIN_ULTIMUM,
	CHALLENGE_LEVEL_BOARD_RAUM,
	CHALLENGE_LEVEL_240_SEKUNDEN_LEGENDAER,
	CHALLENGE_LEVEL_ALLES_ODER_NICHTS,
	CHALLENGE_LEVEL_FINALE_ULTIMUM,
	CHALLENGE_LEVEL_ITEM_KOLOSS,
	CHALLENGE_LEVEL_CHAOS_MEISTER,
	CHALLENGE_LEVEL_60K_PUNKTE,
	CHALLENGE_LEVEL_UEBERLEBENS_ULTIMATE,
	CHALLENGE_LEVEL_ALL_MEISTER,
	CHALLENGE_LEVEL_EXAKT_24,
	CHALLENGE_LEVEL_LEGENDAER_FINAL
} ChallengeLevelId;

/* Initialize challenge state (called when entering state) */
void challenge_init(void);

/* One-time draw when entering challenge state */
void challenge_init_draw(void);

/* Draw the 16x8 grid */
void challenge_draw(void);

/* Handle input every frame */
void challenge_update(void);

/* Check if a level is unlocked */
u8 challenge_is_unlocked(u8 level_id);

/* Check if a level is cleared */
u8 challenge_is_cleared(u8 level_id);

/* Translate grid position to challenge level ordering */
u8 challenge_translate_grid_to_level(u8 grid_id);

/* Get display name for a translated challenge level */
const char* challenge_get_level_name(u8 challenge_level_id);

/* Set level as cleared and unlock neighbors */
void challenge_mark_cleared(u8 level_id);

/* Cleanup when leaving challenge state */
void challenge_cleanup(void);

#endif
